// <auto-generated />
using DataLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataLibrary.Migrations.MockMigrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180407175408_Added emote system to database")]
    partial class Addedemotesystemtodatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AtlasBot.Modules.RoleEmote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DiscordEmoteServerId");

                    b.Property<long>("DiscordRole");

                    b.Property<long>("Emote");

                    b.HasKey("Id");

                    b.HasIndex("DiscordEmoteServerId");

                    b.ToTable("RoleEmotes");
                });

            modelBuilder.Entity("DataLibrary.DiscordEmoteServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("EmoteMessage");

                    b.Property<long>("ServerId");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("DataLibrary.Useraccounts.Implementation.APISummoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Region");

                    b.Property<long>("SummonerId");

                    b.HasKey("Id");

                    b.ToTable("Summoners");
                });

            modelBuilder.Entity("AtlasBot.Modules.RoleEmote", b =>
                {
                    b.HasOne("DataLibrary.DiscordEmoteServer")
                        .WithMany("RoleEmotes")
                        .HasForeignKey("DiscordEmoteServerId");
                });
#pragma warning restore 612, 618
        }
    }
}
